accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from . import views
app_name= "accounts"
urlpatterns = [

    path("login/",views.log_in,name="login"),

    path("signup/",views.sign_up,name="signup"),
    path("logout",views.log_out,name="logout"),
    path("studentform",views.studentform,name = "studentform"),
    path("activate/<str:uidb64>/<str:token>",views.activate,name='activate'),
    #url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),


]

events/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
app_name="events"
urlpatterns = [

    path("",views.eventf,name="event"),
    path("enterevent<int:number>",views.enterevent,name="enterevent"),
    path("p",views.p),
    ]

techfest/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.home,name="home"),
    path("/",include("accounts.urls",namespace="accounts")),
    path("about",views.about,name="about"),
    path("privacy",views.privacy,name="privacy"),
    path("events/",include("events.urls",namespace="events")),
    path("logout",views.log_out,name="logout"),
    path("placement",views.placement,name="placement"),
    path("announcement", views.announcement, name="announcement"),
    path("announcement2/<int:id>/", views.announce, name="announcement2"),
      path("reg",views.reg,name="reg"),


]

accounts/models.py
from django.db import models
from events.models import event

class s_detail(models.Model):
   roll_no = models.CharField(max_length=11,unique=True)
   first_name=models.CharField(max_length=20)
   last_name=models.CharField(max_length=20)  
   dob= models.DateField()
   email=models.EmailField()
   mobile_number=models.CharField(max_length=10)
   gender=models.CharField(max_length=10)
   address=models.CharField(max_length=300)
   city=models.CharField(max_length=10)
   pin_code=models.CharField(max_length=7)
   state=models.CharField(max_length=15)
   language=models.CharField(max_length=50)
   other_l=models.CharField(max_length=11,unique=True)
   degree=models.CharField(max_length=10)

class student(models.Model):
    event=models.ManyToManyField(event)
    username=models.CharField( max_length=30,)
    email=models.EmailField(max_length=40)
    password=models.CharField(max_length=40)
    def __str__(self):
        return self.username

class studentsignup(models.Model):
    dept_name = (('Dept_1', 'BTECH-CSE'),
                 ('Dept_2', 'BTECH-CIVIL'),
                 ('Dept_3', 'BTECH-MECHANICAL'),)

    sem = (('I', 'I'),
           ('II', 'II'),
           ('III', 'III'),
           ('IV', 'IV'),
           ('V', 'V'),
           ('VI', 'VI'),
           ('VII', 'VII'),
           ('VIII', 'VIII'),

           )
    roll_no = models.CharField(max_length=25,unique=True)
    name = models.CharField(max_length = 60)
    department_name = models.CharField(max_length=70, choices=dept_name,
                                       default='Dept_1')
    semester = models.CharField(max_length=10,
                                choices = sem, default='I')
    mobile_number = models.CharField(max_length=10)
    email_id = models.EmailField(max_length=20)
    password = models.CharField(max_length = 100)

    class Meta():
        ordering = ['roll_no']

events/models.py
from django.db import models
import datetime

class event(models.Model):
    name = models.CharField(max_length=100)
    detail=models.TextField()
    image=models.FileField(null=True,blank=True,upload_to="static/events/images")
    date = models.DateTimeField(auto_now=False, auto_now_add=False,null=True,blank=True)
    def __str__(self):
        return self.name




class announcements(models.Model):
    I = 'I'
    II='II'
    III='III'
    IV = 'IV'
    V =  'V'
    VI = 'VI'
    VII = 'VII'
    VIII = 'VIII'
    To_all = 'I-VIII'

    Dept_1='BTECH-CSE'
    Dept_2='BTECH-CIVIL'
    Dept_3='BTECH-MECHANICAL'
    sem = ((I, 'I'),
        (II, 'II'),
        (III, 'III'),
        (IV, 'IV'),
        (V, 'V'),
        (VI, 'VI'),
        (VII, 'VII'),
        (VIII, 'VIII'),
        (To_all,'I-VIII'),
           )
    dept_name = ((Dept_1,'BTECH-CSE'),
                 (Dept_2,'BTECH-CIVIL'),
                 (Dept_3,'BTECH-MECHANICAL'),)

    name =  models.CharField(max_length=100)
    detail=models.TextField()
    image=models.FileField(null=True,blank=True,upload_to="static/events/images")
    image_link = models.CharField(max_length=300, null=True, blank=True)
    department_name = models.CharField(max_length=70, choices=dept_name,
        default=Dept_1)
    semester = models.CharField(max_length=10,
        choices=sem,
        default=I,)
    name_of_announcer = models.CharField(max_length=50,)
    date_of_announcement = models.DateTimeField(auto_now = False)
    def __str__(self):
        return self.name


from django.contrib import admin

admin.site.register(announcements)

events/views.py
from django.shortcuts import render
from .models import event
from django.contrib.auth.models import User


def eventf(request):
    events=event.objects.all()

    print(events)
    print(events)

    return render(request,"events/event.html",{"events":events})
def p(request):
    events=event.objects.all()
    return render(request,"events/p.html",{"events":events})

def enterevent(request,number):

    events = event.objects.filter(id = number)
    return render(request,"events/enterevent.html",{ "events":events})

events/templates/events/enterevent.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    GNDU
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{% static 'css/material-kit.css' %}" rel="stylesheet" />

</head>

<body class="home sidebar-collapse">
  <nav class="navbar bg-dark fixed-top navbar-expand-lg " color-on-scroll="100" id="sectionsNav" role="navigation-demo">
            <div class="container">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-translate">
                <a class="btn btn-rose btn btn-primary" <a href="{% url "home"  %}">Brogrammers</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="navbar-toggler-icon"></span>
                  <span class="navbar-toggler-icon"></span>
                  <span class="navbar-toggler-icon"></span>
                </button>
              </div>
              <!-- Collect the nav links, forms, and other content for toggling -->

              <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <a href="{% url "about" %}" class="nav-link">
                      about
                    </a>
                  </li>
                  <li class="dropdown nav-item">
                    <a href="{% url "events:event" %}" class="nav-link">
                      events
                    </a>
                  </li>
                     <li class="dropdown nav-item">
                    <a href="{% url "placement" %}" class="nav-link">
                      Placement
                    </a>
                  </li>
                    <li class="dropdown nav-item">
                    <a href="{% url "announcement" %}" class="nav-link">
                        Announcements
                    </a>
                  </li>
{% if request.user.is_authenticated %}
                      <li class="nav-item">
                        <div class="col-lg-6 col-md-6">
                            <a href="{% url "logout" %}" class="btn btn-rose btn-round">
                                    <i class="material-icons">account_circle</i>
                                   {{request.user}} Logout
                              </a>
                            </div>
                            </li>
{% else %}
                  <li class="nav-item">
                        <div class="col-lg-6 col-md-6">
                                <button class="btn btn-rose btn-round" data-toggle="modal" data-target="#loginModal">
                                    <i class="material-icons">account_circle</i>
                                    Login
                                </button>
                            </div>
                          </li>
                      <li class="nav-item">
                    <a href="{% url "accounts:signup" %}" class="btn btn-rose btn-round">
                        <i class="material-icons">account_circle</i>
                      Register
                    </a>
                  </li>

{% endif %}
                </ul>
              </div>
              <!-- /.navbar-collapse -->
            </div>
            <!-- /.container-->
          </nav>
        {% if messages %}
<nav class="navbar navbar-transparent fixed-bottom navbar-expand-lg " id="sectionsNav" role="navigation-demo">
   <div class="alert alert-success">
            <div class="container">
                <div class="alert-icon">
                    <i class="material-icons">check</i>
                </div>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true"><i class="material-icons">clear</i></span>
                </button>
                {% for message in messages %}
                <b>  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                </b>

                    {% endfor %}
            </div>
        </div>
        <div class="clearfix"></div>
</nav>
{% endif %}


  <!html form for enter into event>
<br/><br/><br/><br/><br/>
  <form method="" action="">

<table border="1" align="center" width="400" bgcolor="#CCCCCC" >

<caption>Registration form</caption>

<tr>

<th >Enter your first name</th>

<td><input type="text" name="fn" id="fn1" maxlength="10" title="enter your first name" placeholder="enter your first name" required/></td>

</tr>

<tr>

<th>Enter your last name</th>

<td><input type="text" name="ln"/></td>

</tr>







<tr>

<th>Enter your email</th>

<td><input name="email" type="email" required =" "/></td>

</tr>

<tr>

<th>Enter your mobile</th>

<td><input name="mobile"type="number" required=" "/></td>

</tr>

<tr>

<th>Enter your colleage/campus name</th>

<td><input type="text" name="campus"></input></td>

</tr>

<tr>

<th>Select your gender</th>

<td>

male<input type="radio" name="g" value="m"/>
female<input type="radio" name="g" value="f"/>

</td>

</tr>

<tr>

<th>Selected event</th>

<td>

{% for e in events %}

<input name="event" type="text" placeholder={{ e.name }} disabled="disabled">

{% endfor %}}
</td>

</tr>

<tr>

<th>Select your DOB</th>

<td><input type="date" name = "dob"/></td>

</tr>








</td>

</tr>

</table>

</form>





 <script src="{% static 'js/core/jquery.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/core/bootstrap-material-design.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/plugins/moment.min.js' %}"></script>
  <!--  Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
  <script src="{% static 'js/plugins/bootstrap-datetimepicker.js' %}" type="text/javascript"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{% static 'js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
  <!--  Plugin for Sharrre btn -->
  <script src="{% static 'js/plugins/jquery.sharrre.js' %}" type="text/javascript"></script>
  <!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'js/material-kit.js' %}" type="text/javascript"></script>
</body>

</html>

events/templates/events/p.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="css/stylep.css" type="text/css">

    <title>Student participated in particular event</title>
  </head>
  <body>

    <!-- Just an image -->
     <!-- Image and text -->
<nav class="navbar navbar-light bg-dark">
  <a class="navbar-brand" href="http://cess-soc-techfest.herokuapp.com/">
    <h2> <span class="badge badge-secondary badge-danger">Brogrammers</span></h2>

  </a>
</nav>
     <hr></hr>
    {% for e in events %}
       <div class="card">
         <div class="card-header">
           <center><h1>{{ e.name }} participant</h1></center>
         </div>
         <div class="card-body">
            <blockquote class="blockquote mb-0">
              <div class="card" style="width: 18rem;">
                <ul class="list-group list-group-flush">
                  {% for s in e.student_set.all %}
                  <li class="list-group-item">{{ s.username }}</li>
                  <br>
                </ul>
                 {% endfor %}
                 <br>
              </div>
               
        
        
               <footer class="blockquote-footer"> <cite title="Source Title"></cite></footer>
            </blockquote>
        </div>
       </div>
       {% endfor %}
      
      
    

     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>