accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from . import views
app_name= "accounts"
urlpatterns = [

    path("login/",views.log_in,name="login"),

    path("signup/",views.sign_up,name="signup"),
    path("logout",views.log_out,name="logout"),
    path("studentform",views.studentform,name = "studentform"),
    path("activate/<str:uidb64>/<str:token>",views.activate,name='activate'),
    #url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),


]

events/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
app_name="events"
urlpatterns = [

    path("",views.eventf,name="event"),
    path("enterevent<int:number>",views.enterevent,name="enterevent"),
    path("p",views.p),
    ]

techfest/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.home,name="home"),
    path("/",include("accounts.urls",namespace="accounts")),
    path("about",views.about,name="about"),
    path("privacy",views.privacy,name="privacy"),
    path("events/",include("events.urls",namespace="events")),
    path("logout",views.log_out,name="logout"),
    path("placement",views.placement,name="placement"),
    path("announcement", views.announcement, name="announcement"),
    path("announcement2/<int:id>/", views.announce, name="announcement2"),
      path("reg",views.reg,name="reg"),


]

accounts/models.py
from django.db import models
from events.models import event

class s_detail(models.Model):
   roll_no = models.CharField(max_length=11,unique=True)
   first_name=models.CharField(max_length=20)
   last_name=models.CharField(max_length=20)  
   dob= models.DateField()
   email=models.EmailField()
   mobile_number=models.CharField(max_length=10)
   gender=models.CharField(max_length=10)
   address=models.CharField(max_length=300)
   city=models.CharField(max_length=10)
   pin_code=models.CharField(max_length=7)
   state=models.CharField(max_length=15)
   language=models.CharField(max_length=50)
   other_l=models.CharField(max_length=11,unique=True)
   degree=models.CharField(max_length=10)

class student(models.Model):
    event=models.ManyToManyField(event)
    username=models.CharField( max_length=30,)
    email=models.EmailField(max_length=40)
    password=models.CharField(max_length=40)
    def __str__(self):
        return self.username

class studentsignup(models.Model):
    dept_name = (('Dept_1', 'BTECH-CSE'),
                 ('Dept_2', 'BTECH-CIVIL'),
                 ('Dept_3', 'BTECH-MECHANICAL'),)

    sem = (('I', 'I'),
           ('II', 'II'),
           ('III', 'III'),
           ('IV', 'IV'),
           ('V', 'V'),
           ('VI', 'VI'),
           ('VII', 'VII'),
           ('VIII', 'VIII'),

           )
    roll_no = models.CharField(max_length=25,unique=True)
    name = models.CharField(max_length = 60)
    department_name = models.CharField(max_length=70, choices=dept_name,
                                       default='Dept_1')
    semester = models.CharField(max_length=10,
                                choices = sem, default='I')
    mobile_number = models.CharField(max_length=10)
    email_id = models.EmailField(max_length=20)
    password = models.CharField(max_length = 100)

    class Meta():
        ordering = ['roll_no']

accounts/forms.py
from django import forms
from .models import studentsignup
from django.contrib.auth.models import User

class studentreg(forms.ModelForm):
    sem = (('I', 'I'),
           ('II', 'II'),
           ('III', 'III'),
           ('IV', 'IV'),
           ('V', 'V'),
           ('VI', 'VI'),
           ('VII', 'VII'),
           ('VIII', 'VIII'),

           )

    dept_name = (('Dept_1', 'BTECH-CSE'),
                 ('Dept_2', 'BTECH-CIVIL'),
                 ('Dept_3', 'BTECH-MECHANICAL'),)
    roll_no = forms.CharField(widget = forms.TextInput(),required = True,max_length=25)
    name = forms.CharField(widget = forms.TextInput(),required = True,max_length=60)
    department_name = forms.ChoiceField(choices=dept_name,required = True)
    semester = forms.ChoiceField(choices=sem,required = True)

    mobile_number = forms.CharField(widget = forms.TextInput(),required = True,max_length=10)
    email_id = forms.EmailField(widget = forms.EmailInput(),required = True,max_length=20)
    password = forms.CharField(widget = forms.PasswordInput(),required = True,max_length=100)

    class Meta():
        ordering = ['roll_no']
        model = studentsignup
        fields = ['roll_no','name','department_name','semester','mobile_number','email_id','password']



class userform(forms.ModelForm):

    first_name = forms.CharField(widget= forms.TextInput(attrs={'placeholder':'First Name'}),required = True,max_length=30)
    last_name = forms.CharField(widget = forms.TextInput(attrs={'placeholder':'Last Name'}),max_length = 30)
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder':'Email'}),required=True,max_length=50)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password'}),required = True,max_length= 50)
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password'}),required=True,max_length=50)

    class Meta:
        model = User
        fields = ('first_name','last_name','email','password')

accounts/views.py
from django.shortcuts import render,redirect,HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from .models import student
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import studentreg , userform
from .models import studentsignup
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage




def log_out(request):
    logout(request)
    return redirect(('home'))
def log_in(request):

        if request.method=="POST":
            print(request.POST)
            u=request.POST.get("username")
            p=request.POST.get("password")
            user=authenticate(request,username=u,password=p)
            if user is not None:
                login(request,user)
                messages.success(request, ' Welcome to Tech Fest '+ u )
                return redirect("home")
        return render(request,'accounts/login.html')


"""def sign_up(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            s=student(username=username,password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/register.html', {'form': form})"""

def studentform(request):

    if request.method == 'POST':
        form = studentreg(request.POST)
        if form.is_valid():
            form.save()

            messages.success(request,'you details submiited ')
            return HttpResponseRedirect('')
    else:
        form = studentreg()

    return render(request,'accounts/studentform.html',{'form':form})


def sign_up(request):
    if request.method == 'POST':
        form1 = userform(request.POST)
        if form1.is_valid():
            username = form1.cleaned_data['email']
            first_name = form1.cleaned_data['first_name']
            last_name = form1.cleaned_data['last_name']
            email = form1.cleaned_data['email']
            password=form1.cleaned_data['password']
            user= User.objects.create_user(username=username,first_name=first_name,last_name =last_name,email=email,password =password,is_active=False)
            current_site = get_current_site(request)
            uid3 =User.objects.get(pk=user.pk),
            #encod = user.email.encode('base64','strict'),
            userdetail = {'user': username,
                'domain': current_site.domain,
                #'encod':encod,
                'uid2':User.objects.get(pk=user.pk),

                'uid': urlsafe_base64_encode(force_bytes(uid3)),

                'token': account_activation_token.make_token(user)}
            message = "hii "+ userdetail['user']+"\nclick on link "+userdetail['domain']+"/accounts/activate"+"/"+str(userdetail['uid2'])+"/"+str(userdetail['token'])
            mail_subject = 'Activate your blog account.'
            to_email = form1.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')

            return HttpResponseRedirect('')

    else:
        form1 = userform()
    return render(request,'accounts/register.html',{'form':form1})


def activate(request, uidb64, token):
    try:

        #uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(username=uidb64)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        u=user.first_name
        # return redirect('home')
        messages.success(request, ' link activated ' + u)
        return redirect("home")
    else:
        return HttpResponse('Activation link is invalid!')

accounts/templates/accounts/acc_active_email.html
{% autoescape off %}
Hi {{ userdetail.username }},
Please click on the link to confirm your registration,
http://{{ userdetail.domain }}
{% endautoescape %}

accounts/templates/accounts/demo.html
{{ form }}

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    GNDU
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{% static 'css/material-kit.css' %}" rel="stylesheet" />

</head>

<body class="login-page sidebar-collapse">
  <nav class="navbar navbar-color-on-scroll navbar-transparent fixed-top navbar-expand-lg " color-on-scroll="100" id="sectionsNav" role="navigation-demo">
            <div class="container">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-translate">
                <a class="btn btn-rose btn btn-primary" <a href="{% url "home"  %}">Brogrammers</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="navbar-toggler-icon"></span>
                  <span class="navbar-toggler-icon"></span>
                  <span class="navbar-toggler-icon"></span>
                </button>
              </div>
              <!-- Collect the nav links, forms, and other content for toggling -->

              <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <a href="about link" class="nav-link">
                      about
                    </a>
                  </li>
                  <li class="dropdown nav-item">
                    <a href="{% url "events:event" %}" class="nav-link">
                      events
                    </a>
                  </li>

{% if request.user.is_authenticated %}
                      <li class="nav-item">
                        <div class="col-lg-6 col-md-6">
                            <a href="{% url "logout" %}" class="btn btn-rose btn-round">
                                    <i class="material-icons">account_circle</i>

                                   {{request.user}} Logout
                              </a>
                            </div>
                            </li>
{% else %}

                      <li class="nav-item">
                        <div class="col-lg-6 col-md-6">
                                <button class="btn btn-rose btn-round" data-toggle="modal" data-target="#loginModal">
                                    <i class="material-icons">account_circle</i>
                                    Login
                                </button>
                            </div>
                      </li>
                       <li class="button-container nav-item iframe-extern">
                    <a href="{% url 'accounts:signup' %}" target="_blank" class="btn  btn-rose   btn-round btn-block">
                         Signup
                    </a>
                </li>
{% endif %}
                </ul>
              </div>
              <!-- /.navbar-collapse -->
            </div>
            <!-- /.container-->
          </nav>

      {% if messages %}
        <ul class="messages" color=#ffffff>
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
      {% endif %}
          <form accept-charset="UTF-8" role="form" method="post">
                {% csrf_token %}

<div class="modal fade" id="loginModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-login" role="document">
        <div class="modal-content">
            <div class="card card-signup card-plain">
                <div class="modal-header">
                    <div class="card-header card-header-primary text-center">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="material-icons">clear</i></button>
                        <h4 class="card-title">Log in</h4>
                        <div class="social-line">
                          <a href="#pablo" class="btn btn-just-icon btn-link">
                            <i class="fa fa-facebook-square"></i>
                          </a>
                          <a href="#pablo" class="btn btn-just-icon btn-link">
                            <i class="fa fa-twitter"></i>
                          </a>
                          <a href="#pablo" class="btn btn-just-icon btn-link">
                            <i class="fa fa-google-plus"></i>
                          </a>
                        </div>
                    </div>
                </div>
                <div class="modal-body">
                    <form class="form" method="" action="">
                        <p class="description text-center">Or Be Classical</p>
                        <div class="card-body">

                            <div class="form-group">
                                <div class="input-group">
                                  <div class="input-group-prepend">
                                    <span class="input-group-text">
                                      <i class="material-icons">face</i>
                                    </span>
                                  </div>
                                  <input type="text" name="username" class="form-control" placeholder="User Name...">
                                </div>
                            </div>

                            <!-- <div class="form-group">
                                <div class="input-group">
                                  <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="material-icons">mail</i>
                                    </span>
                                  </div>
                                    <input type="text" class="form-control" placeholder="Email...">
                                </div>
                            </div> -->

                            <div class="form-group">
                                <div class="input-group">
                                  <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="material-icons">lock_outline</i>
                                    </span>
                                  </div>
                                  <input type="password" name="password" placeholder="Password..." class="form-control" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer justify-content-center">

                        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Login">
                </div>
            </div>
        </div>
    </div>
</div>
    </form>
    <div class="page-header header-filter" style="background-image: url('{% static 'img/bg7.jpg' %}'); background-size: cover; background-position: top center;">
<div class="container">
<div class="row">
  <div class="col-lg-4 col-md-6 ml-auto mr-auto">
    <div class="card card-login">
        <form class="form" method="" action="">
          <div class="card-header card-header-primary text-center">
            <h4 class="card-title">Log in</h4>
            <div class="social-line">
              <a href="#pablo" class="btn btn-just-icon btn-link">
                <i class="fa fa-facebook-square"></i>
              </a>
              <a href="#pablo" class="btn btn-just-icon btn-link">
                <i class="fa fa-twitter"></i>
              </a>
              <a href="#pablo" class="btn btn-just-icon btn-link">
                <i class="fa fa-google-plus"></i>
              </a>
            </div>
          </div>
          <p class="description text-center">Or Be Classical</p>
          <div class="card-body">

            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text">
                    <i class="material-icons">face</i>
                </span>
              </div>
              <input type="text" class="form-control" placeholder="First Name...">
            </div>

            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text">
                    <i class="material-icons">mail</i>
                </span>
              </div>
              <input type="email" class="form-control" placeholder="Email...">
            </div>

            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text">
                    <i class="material-icons">lock_outline</i>
                </span>
              </div>

              <input type="password" class="form-control" placeholder="Password...">
            </div>

            <!-- If you want to add a checkbox to this form, uncomment this code

            <div class="checkbox">
              <label>
                <input type="checkbox" name="optionsCheckboxes" checked>
                Subscribe to newsletter
              </label>
            </div> -->
          </div>
          <div class="footer text-center">
            <a href="#pablo" class="btn btn-primary btn-link btn-wd btn-lg">Get Started</a>
          </div>
        </form>
      </div>
  </div>
</div>
</div>


  <footer class="footer footer-default">
    <div class="container">
      <nav class="float-left">
        <ul>
          <li>
            <a href="home link">
              Brogrammers
            </a>
          </li>
          <li>
            <a href="about us link">
              About Us
            </a>
          </li>
            <a href="terms and conditions link">
              terms and conditions
            </a>
          </li>
        </ul>
      </nav>
      <div class="copyright float-right">
        &copy;
        <script>
          document.write(new Date().getFullYear())
        </script>, made with <i class="material-icons">favorite</i> by
        <a href="https://www.creative-tim.com" target="_blank">Brogrammers</a> for a (stupid) project.
      </div>
    </div>
  </footer>
  <!--   Core JS Files   -->
  <script src="{% static 'js/core/jquery.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/core/bootstrap-material-design.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/plugins/moment.min.js' %}"></script>
  <!--  Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
  <script src="{% static 'js/plugins/bootstrap-datetimepicker.js' %}" type="text/javascript"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{% static 'js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
  <!--  Plugin for Sharrre btn -->
  <script src="{% static 'js/plugins/jquery.sharrre.js' %}" type="text/javascript"></script>
  <!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'js/material-kit.js' %}" type="text/javascript"></script>
</body>

</html>

accounts/templates/accounts/register.html
{% extends "comman.html" %}
{% load static %}

{% block content %}
      <br/><br/>
      {% if messages %}
        <ul class="messages" color=#ffffff>
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
      {% endif %}
          <form accept-charset="UTF-8" role="form" method="post">
                {% csrf_token %}

<div class="modal fade" id="loginModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-login" role="document">
        <div class="modal-content">
            <div class="card card-signup card-plain">
                <div class="modal-header">
                    <div class="card-header card-header-primary text-center">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="material-icons">clear</i></button>
                        <h4 class="card-title">Log in</h4>
                        <div class="social-line">
                          <a href="#pablo" class="btn btn-just-icon btn-link">
                            <i class="fa fa-facebook-square"></i>
                          </a>
                          <a href="#pablo" class="btn btn-just-icon btn-link">
                            <i class="fa fa-twitter"></i>
                          </a>
                          <a href="#pablo" class="btn btn-just-icon btn-link">
                            <i class="fa fa-google-plus"></i>
                          </a>
                        </div>
                    </div>
                </div>
                <div class="modal-body">
                    <form class="form" method="" action="">
                        <p class="description text-center">Or Be Classical</p>
                        <div class="card-body">

                            <div class="form-group">
                                <div class="input-group">
                                  <div class="input-group-prepend">
                                    <span class="input-group-text">
                                      <i class="material-icons">face</i>
                                    </span>
                                  </div>
                                  <input type="text" name="username" class="form-control" placeholder="User Name...">
                                </div>
                            </div>

                            <!-- <div class="form-group">
                                <div class="input-group">
                                  <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="material-icons">mail</i>
                                    </span>
                                  </div>
                                    <input type="text" class="form-control" placeholder="Email...">
                                </div>
                            </div> -->

                            <div class="form-group">
                                <div class="input-group">
                                  <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="material-icons">lock_outline</i>
                                    </span>
                                  </div>
                                  <input type="password" name="password" placeholder="Password..." class="form-control" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer justify-content-center">

                        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Login">
                </div>
            </div>
        </div>
    </div>
</div>
    </form>


     <!-- Register -->


<div class="page-header header-filter" filter-color="purple" style="background-image: url('{% static 'img/bg7.jpg' %}'); background-size: cover; background-position: top center;">
  <div class="container">
  <div class="">
      <div class="">
      <div class="card card-signup">
        <h2 class="card-title text-center">Register</h2>
        <div class="card-body">
          <!-- <div class="row">
            <div class="col-md-5 ml-auto">
              <div class="info info-horizontal">
                <div class="icon icon-rose">
                  <i class="material-icons">timeline</i>
                </div>
                <div class="description">
                  <h4 class="info-title">Marketing</h4>
                  <p class="description">
                    We've created the marketing campaign of the website. It was a very interesting collaboration.
                  </p>
                </div>
              </div>

              <div class="info info-horizontal">
                <div class="icon icon-primary">
                  <i class="material-icons">code</i>
                </div>
                <div class="description">
                  <h4 class="info-title">Fully Coded in HTML5</h4>
                  <p class="description">
                    We've developed the website with HTML5 and CSS3. The client has access to the code using GitHub.
                  </p>
                </div>
              </div>

              <div class="info info-horizontal">
                <div class="icon icon-info">
                  <i class="material-icons">group</i>
                </div>
                <div class="description">
                  <h4 class="info-title">Built Audience</h4>
                  <p class="description">
                    There is also a Fully Customizable CMS Admin Dashboard for this product.
                  </p>
                </div>
              </div>
            </div> -->

           
             

                  {{ stu }}


<!-- register form  -->
              <form class="form" method="post" action="">
            {%    csrf_token %}

                <!-- <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text">
                          <i class="material-icons">face</i>
                      </span>
                    </div>
                    <input type="text" class="form-control" name="username" placeholder="Username...">
                  </div>
                </div> -->

                <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text">
                          <i class="material-icons"></i>
                      </span>
                    </div >

                  </div>
                </div>

                <!-- <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text">
                          <i class="material-icons">lock_outline</i>
                      </span>
                    </div> -->
              <form method = "post" action="">
              	<div class="text-center">
    
    
           
    
     {% csrf_token %}
   	{{ form.as_p }}
      
   

 
    	</div>
    
 
    			</div>
               <!-- sss  <input type="password" name="password1" placeholder="Password..." class="form-control" />
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text">
                          <i class="material-icons">lock_outline</i>
                      </span>
                    </div>
                    <input type="password" name="password2" placeholder=" conform Password..." class="form-control" />
                  </div>
                </div>
                <div class="form-check">
                  <label class="form-check-label">
                    <input class="form-check-input" type="checkbox" value="" checked>
                    <span class="form-check-sign">
                      <span class="check"></span>
                    </span>
                    I agree to the <a href="#something">terms and conditions</a>.
                  </label>
                </div>

--> <div class="text-center">
    <button type="submit" class="btn btn-primary btn-round">Get Started</button>
    <a href="{% url 'accounts:login' %}" ></a>
  </div>
</form>

            </div>
          </div>
        </div>
      </div>
            </div>
        </div>
  
{% endblock %}

accounts/templates/accounts/studentform.html
{% extends "comman.html" %}

   {% block content %}
 <br/><br/><br/><br/>
   {% if messages %}
   <div class="alert alert-success" role="alert">
   {% for message in messages %}
   <div>{{ message }}</div>
   {% endfor %}
   </div>
   {% endif %}

   <form method = 'post' action = " " >
       {% csrf_token %}
       <div >
           {{ form.as_p }}
       </div>
       <button type = "submit">Submit </button>

       {% endblock %}